### ISSUE TITLE
What is default image preloading behavior?

### ISSUE THREAD

**Issue by syedabdulbaqi** [archriss/react-native-image-gallery#19]
What is default image preloading behavior? How many images will be loaded by default?

**Comment by Exilz** [comment]
Since `v2.0.0`, this module relies on `FlatList`. This is the only thing that will affect the rendering logic of each image.

For now, I left the optional optimizations of the component blank. I will keep an eye on the performance of galleries with a large number of items and/or big images and see if it's important to either provide these optional props for `FlatList`, or at least let the users provide their own if they need to tweak it.

So, to give you an answer, if `FlatList` is behaving how react-native describes it, it *should* render enough images to fill the whole list horizontally, so, only one.

Actually, I'm pretty sure it's not doing that behind the scenes. `FlatList` is far from being totally finished and is still riddled with bugs and regressions across versions.

I don't want to over-optimize things yet, but if the need arises we'll release a version that renders items in a more optimized way, especially on the first render.

**Comment by vbuch** [comment]
By default FlatList renders the currently viewed screen + 10 more in any direction. This means you ould normally end up with 21 rendered screens.

**Comment by vbuch** [comment]
It is not well documented, yes. But it describes where you should fetch docs from. Since FlatList is actually a VirtualizedList: https://facebook.github.io/react-native/docs/virtualizedlist.html#windowsize

**Comment by vbuch** [comment]
So in the case of this image gallery setting `windowSize={3}` should be exactly what's needed.

**Comment by Exilz** [comment]
I didn't know about this prop, it might be good to allow users to pass props to `FlatList` directly then.

**Comment by vbuch** [comment]
Having it set to 3 by default is a good idea though. In most usecases of the gallery you would only need three. You cannot actually scroll past a couple of images, right?

**Comment by syedabdulbaqi** [comment]
I agree with @vbuch, preloading 10 images at the startup is causing initial render of the application slower. This is the reason I rolled back to version 1.1.0 and wrote my own logic using Image.prefetch to preload 3 images.

Version 1.1.0 was not showing any default preloading behavior.

**Comment by vbuch** [comment]
@syedabdulbaqi you could give this [pull request](https://github.com/archriss/react-native-image-gallery/pull/21) a try and confirm if @Exilz should review it.
