### ISSUE TITLE
Gallery needs to be rendered with some delay on iOS with react-navigation

### ISSUE THREAD

**Issue by ou2s** [archriss/react-native-image-gallery#35]
I'm using version 2.1.3 and images are not displayed when coming from a React Navigation Screen on iOS.

When calling the component containing the Gallery outside of a React Navigation screen, the library works as expected.

React Native: 0.48.4
React Navigation: 1.0.0-beta.19

**Comment by ou2s** [comment]
Solved the issue on iOS by making sure that Gallery is not rendered until InteractionManager.runAfterInteractions is called.

**Comment by Exilz** [comment]
Thanks for sharing your solution, this might be the same problem as #25 and #29.
I'm not really sure why this is happening, we never encountered this error @archriss since we always use runAfterInteractions or some sort of timeout to ease up the rendering during navigation.

This would need to be investigated furthermore. In the meantime, this is a nice and clean workaround. Much better than wrapping the view in a `ScrollView`, as stated in the other issue. I guess it must trigger some kind of re-render, hence displaying the gallery.

**Comment by ou2s** [comment]
I also had a bug when going back to a previous screen. The bug was the following:
```
TaskQueue: Error with task : undefined is not an object 
(evaluating '_this3.refs['innerFlatList'].scrollToOffset')
```

I solved it by making sure that the Gallery is not rendered before calling `navigation.goBack()`.

By the way, thanks for this library, I find it better than the other alternatives because it supports orientation and the code is clean.
